// export const UPDATE_FACTORY_MANAGER_LOGIN = 'UPDATE_FACTORY_MANAGER_LOGIN';

export const LOGIN='LOGIN';
export const VERIFY_OTP='VERIFY_OTP';
export const SIGNUP='SIGNUP';

export const ADD_SOURCE = 'ADD_SOURCE';
export const GET_SOURCE = 'GET_SOURCE';

export const ADD_CORDINATOR_TYPE = 'ADD_CORDINATOR_TYPE';
export const GET_CORDINATOR_TYPE = 'GET_CORDINATOR_TYPE';

export const ADD_CORDINATOR = 'ADD_CORDINATOR';
export const GET_CORDINATOR = 'GET_CORDINATOR';

export const GET_CORDINATOR_BY_ID = 'GET_CORDINATOR_BY_ID';

export const ADD_FACTORY = 'ADD_FACTORY';
export const GET_FACTORY = 'GET_FACTORY';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';

export const ADD_STATUS = 'ADD_STATUS';
export const GET_STATUS = 'GET_STATUS';

export const ADD_STATUS_ACTION = 'ADD_STATUS_ACTION';
export const GET_STATUS_ACTION = 'GET_STATUS_ACTION';

export const ADD_SNAG_ACTION = 'ADD_SNAG_ACTION';
export const GET_SNAG_ACTION = 'GET_SNAG_ACTION';

export const ADD_SNAG_ISSUE = 'ADD_SNAG_ISSUE';
export const GET_SNAG_ISSUE = 'GET_SNAG_ISSUE';

export const ADD_SNAG_COST = 'ADD_SNAG_COST';
export const GET_SNAG_COST = 'GET_SNAG_COST';

export const ADD_SNAG_SOLUTION = 'ADD_SNAG_SOLUTION';
export const GET_SNAG_SOLUTION = 'GET_SNAG_SOLUTION';

export const ADD_CARCASS = 'ADD_CARCASS';
export const GET_CARCASS = 'GET_CARCASS';

export const ADD_DESIGNER = 'ADD_DESIGNER';
export const GET_DESIGNER = 'GET_DESIGNER';

 export const ADD_FINAL_SITE_SURVEYOR='ADD_FINAL_SITE_SURVEYOR';
 export const GET_FINAL_SITE_SURVEYOR ='GET_FINAL_SITE_SURVEYOR';

 export const ADD_PLANNER = 'ADD_PLANNER';
export const GET_PLANNER = 'GET_PLANNER';

export const ADD_LOCATION = 'ADD_LOCATION';
export const GET_LOCATION = 'GET_LOCATION';

export const ADD_SALES_PERSON = 'ADD_SALES_PERSON';
export const GET_SALES_PERSON = 'GET_SALES_PERSON';

export const ADD_SHUTTER = 'ADD_SHUTTER';
export const GET_SHUTTER = 'GET_SHUTTER';

export const ADD_FACTORY_ENGINEER = 'ADD_FACTORY_ENGINEER';
export const GET_FACTORY_ENGINEER = 'GET_FACTORY_ENGINEER';

export const ADD_ROLE_ACCESS = 'ADD_ROLE_ACCESS';
export const GET_ROLE_ACCESS = 'GET_ROLE_ACCESS';

export const ADD_ASSISTANT_USER = 'ADD_ASSISTANT_USER';
export const GET_ASSISTANT_USER = 'GET_ASSISTANT_USER';

export const ADD_ENQUIRY = 'ADD_ENQUIRY';
export const GET_ENQUIRY = 'GET_ENQUIRY';

export const ADD_ORDER = 'ADD_ORDER';
export const GET_ORDER = 'GET_ORDER';

export const GET_ORDER_COUNT = 'GET_ORDER_COUNT';
export const GET_ENQUIRY_COUNT = 'GET_ENQUIRY_COUNT';